// Banque de questions du mini-jeu Histoire-Géo (niveau Terminale + culture générale).
export const QUESTIONS_HG = [
  { q: 'En quelle année le Sénégal accède-t-il à l’indépendance ?', c: ['1957', '1960', '1963', '1946'], b: 1, e: 'Le 20 juin 1960, avec Léopold Sédar Senghor comme premier président.' },
  { q: 'Qui a écrit « Une si longue lettre » ?', c: ['Ousmane Sembène', 'Mariama Bâ', 'Senghor', 'Fatou Diome'], b: 1, e: 'Mariama Bâ (1979), prix Noma, monument de la littérature africaine.' },
  { q: 'La guerre froide oppose…', c: ['USA et URSS', 'France et Angleterre', 'Chine et Japon', 'Nord et Sud'], b: 0, e: 'De 1947 à 1991, deux blocs : capitaliste (USA) et communiste (URSS).' },
  { q: 'Quelle est la capitale de l’Australie ?', c: ['Sydney', 'Melbourne', 'Canberra', 'Auckland'], b: 2, e: 'Piège classique : Sydney est la plus grande ville, mais Canberra est la capitale.' },
  { q: 'La conférence de Bandung, c’est…', c: ['1945', '1955', '1960', '1963'], b: 1, e: '1955 : 29 pays d’Asie et d’Afrique refusent de choisir un bloc → les non-alignés.' },
  { q: 'Qui a écrit « Du contrat social » ?', c: ['Voltaire', 'Rousseau', 'Montesquieu', 'Diderot'], b: 1, e: 'Rousseau (1762) : la souveraineté appartient au peuple.' },
  { q: 'Le mur de Berlin tombe en…', c: ['1985', '1989', '1991', '2001'], b: 1, e: '9 novembre 1989 ; l’URSS éclate en 1991.' },
  { q: 'Lequel N’EST PAS membre de la CEDEAO ?', c: ['Nigeria', 'Ghana', 'Maroc', 'Sénégal'], b: 2, e: 'Le Maroc est au Maghreb (UMA), pas en Afrique de l’Ouest.' },
  { q: 'Qui fut le premier président du Sénégal ?', c: ['Abdou Diouf', 'Senghor', 'Mamadou Dia', 'Abdoulaye Wade'], b: 1, e: 'Senghor (1960-1980), puis Diouf.' },
  { q: 'Premier producteur mondial de cacao ?', c: ['Ghana', 'Côte d’Ivoire', 'Nigeria', 'Cameroun'], b: 1, e: 'La Côte d’Ivoire fournit ~40 % du cacao mondial — d’où le prix du chocolat.' },
  { q: 'Le détroit d’Ormuz est stratégique pour…', c: ['le blé', 'le pétrole', 'le riz', 'le charbon'], b: 1, e: '~20 % du pétrole mondial y transite : un blocage = prix qui flambent.' },
  { q: 'Le « Manifeste du parti communiste » est écrit par…', c: ['Lénine', 'Marx et Engels', 'Staline', 'Keynes'], b: 1, e: '1848 : Karl Marx et Friedrich Engels.' },
  { q: 'L’OIF (Francophonie) a son siège à…', c: ['Dakar', 'Paris', 'Genève', 'Bruxelles'], b: 1, e: 'Paris ; le Sommet réunit 88 États et gouvernements.' },
  { q: 'La monnaie du Nigeria ?', c: ['Cedi', 'Naira', 'Shilling', 'Livre'], b: 1, e: 'Le naira ; le cedi est celui du Ghana.' },
  { q: 'Quel océan borde le Sénégal ?', c: ['Pacifique', 'Indien', 'Atlantique', 'Arctique'], b: 2, e: 'L’Atlantique : 700 km de côte, un atout pêche et commerce.' },
  { q: 'Qui a mené la lutte pour les droits civiques aux USA ?', c: ['Malcolm X seul', 'Martin Luther King', 'Obama', 'Lincoln'], b: 1, e: 'Martin Luther King (« I have a dream », 1963), prix Nobel de la paix 1964.' },
  { q: 'La Grande Muraille verte passe par le Sénégal ?', c: ['Vrai', 'Faux'], b: 0, e: 'Vrai : lancée en 2005, son agence panafricaine est basée à Dakar.' },
  { q: 'Qui a peint « Guernica » ?', c: ['Dalí', 'Picasso', 'Miró', 'Goya'], b: 1, e: 'Picasso (1937), cri contre le bombardement de Guernica.' },
  { q: 'L’ONU est créée en…', c: ['1919', '1945', '1948', '1960'], b: 1, e: '1945, après la Seconde Guerre mondiale, pour maintenir la paix.' },
  { q: 'Pays le plus peuplé d’Afrique ?', c: ['Éthiopie', 'Égypte', 'Nigeria', 'RDC'], b: 2, e: '~220 millions d’habitants : un Africain sur 6 est Nigérian.' },
  { q: 'En 1929, que se passe-t-il à Wall Street ?', c: ['Krach boursier', 'Fin de la guerre', 'Création de l’ONU', 'New Deal'], b: 0, e: 'Le krach déclenche la Grande Dépression ; Roosevelt répondra avec le New Deal.' },
  { q: 'Les accords d’Oslo (1993) concernent…', c: ['le Vietnam', 'Israël-Palestine', 'l’Algérie', 'l’Afrique du Sud'], b: 1, e: 'Première reconnaissance mutuelle entre Israël et l’OLP.' },
  { q: 'Quel fleuve traverse le Sénégal ?', c: ['Niger', 'Gambie', 'Congo', 'Nil'], b: 1, e: 'La Gambie (et le fleuve Sénégal au nord, frontière avec la Mauritanie).' },
  { q: '« L’Étranger » est un roman de…', c: ['Camus', 'Sartre', 'Zola', 'Hugo'], b: 0, e: 'Albert Camus (1942), un classique des programmes de français.' },
];
